# Generated by Django 6.0.6 on 2026-06-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(default='Codecademy', max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('credential_type', models.CharField(choices=[('career_path', 'Career Path'), ('skill_path', 'Skill Path'), ('course', 'Course'), ('professional_cert', 'Professional Certification')], max_length=30)),
                ('summary', models.TextField(blank=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('certificate_id', models.CharField(blank=True, max_length=50)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificate_images/')),
                ('skills_text', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('skill_areas', models.ManyToManyField(blank=True, related_name='credentials', to='learning.skillarea')),
            ],
            options={
                'ordering': ['order', '-completed_at', 'title'],
            },
        ),
    ]
