# Generated by Django 6.0.6 on 2026-06-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField()),
                ('client_type', models.CharField(blank=True, max_length=120)),
                ('problem', models.TextField(blank=True)),
                ('context', models.TextField(blank=True)),
                ('goal', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('credentials', models.ManyToManyField(blank=True, related_name='projects', to='learning.learningcredential')),
                ('services', models.ManyToManyField(blank=True, related_name='projects', to='services.service')),
                ('categories', models.ManyToManyField(blank=True, to='portfolio.projectcategory')),
                ('technologies', models.ManyToManyField(blank=True, to='portfolio.technology')),
            ],
        ),
    ]
